spring:
  application:
    name: Library Management
  datasource:
    password: ${DB_PASSWORD}
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
  security:
    secret-key: ${JWT_SECRET_KEY}
